name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: tentcowork-frontend/package-lock.json

      - name: Install dependencies
        run: |
          cd tentcowork-frontend
          npm ci

      - name: Build project
        run: |
          cd tentcowork-frontend
          npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TENTCOWORK_ESTUDIANTES_V2 }}'
          channelId: live
          projectId: tentcowork-estudiantes-v2
          entryPoint: './tentcowork-frontend'